# color configuration
set -g default-terminal "screen-256color"

# Set window configuration as 'vi'
setw -g mode-keys vi

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind = split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# switch panes using 'hjkl' without prefix
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# reload tmux config
unbind r
bind r source-file ~/.tmux.conf# display "Reloaded"
