# Automatically set window title
#set-window-option -g automatic-rename on
#set -g default-terminal "tmux-256color"
set-option -g set-titles on

# color configuration
set -g default-terminal $TERM

setw -g aggressive-resize on

###############################################################
# => Key Bindings
###############################################################

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind s split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# switch panes using 'hjkl'
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-h select-pane -L
bind -n M-l select-pane -R

# bind -n M-j resize-pane -D 5
# bind -n M-k resize-pane -U 5
# bind -n M-h resize-pane -L 5
# bind -n M-l resize-pane -R 5

# Shift arrow to switch windows
bind -n M-Left  previous-window
bind -n M-Right next-window

# open up todo
unbind t
bind t split-window -l 15 vim ~/savio.todo

# Set window configuration as 'vi'
setw -g mode-keys vi

# reload tmux config
unbind r
bind r source-file ~/.tmux.conf\; display-message "Reloaded"
