-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--
-- return {
--   "nvim-telescope/telescope.nvim",
--   keys = {
--     {
--       "<leader><leader>",
--       function()
--         require("telescope.builtin").find_files({ hidden = true })
--       end,
--       desc = "Find Files (with hidden)",
--     },
--   },
-- }
