# Change trigger from CTRL+b to CTRL+a
unbind C-b
set -g prefix C-a

###############################################################
# => Options
###############################################################
# Automatically set window title
set -g set-titles on
setw -g aggressive-resize on
# Enable mouse selections
#set-option -g mouse on
# Set base index for windows to 1 instead of 0
set -g base-index 1
# Set base index for panes to 1 instead of 0
setw -g pane-base-index 1
# vi-like bindings for navigating a buffer in a window
set-window-option -g mode-keys vi

###############################################################
# => Theme
###############################################################
# Right status: Kubernetes context, see https://github.com/jonmosco/kube-tmux
# and AWS context, see https://github.com/mhausenblas/aws-tmux
set -g status-right "#(bash ~/.tmux/kube/kube.tmux 250 red white)"
# set -g status-right "#(bash ~/.tmux/aws/aws.tmux)"

###############################################################
# => Key Bindings
###############################################################
# Ensure that we can send Ctrl-A to other apps
bind C-a send-prefix

# Edit the tmux.conf File with trigger+e
bind e send-keys "vim ~/.tmux.conf" "Enter"\;

# split panes using | and -
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# switch panes using 'hjkl'
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-h select-pane -L
bind -n M-l select-pane -R

# Shift arrow to switch windows
bind -n M-Left  previous-window
bind -n M-Right next-window

# open up todo
unbind t
bind t split-window -l 15 vim ~/savio.todo

# Copy and pipe to clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Source ~/.bashrc with trigger+b
bind b send-keys "source ~/.bashrc" "Enter" \; display ".bashrc sourced :)"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# color configuration
set -g default-terminal $TERM

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
