#!/bin/bash

###
# Bash Completions
###
command -v kubectl >/dev/null && source <(kubectl completion bash)

ctop() {
  docker run --rm -ti \
    --name=ctop \
    --volume /var/run/docker.sock:/var/run/docker.sock:ro \
    quay.io/vektorlab/ctop:latest "$@"
}

open(){
  path=${1:-"."}

  xdg-open $path
}

sshcheck(){
  cmd=${1:-"help"}
  docker run --rm -ti  drwetter/testssl.sh:3.1dev $cmd
}
